# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a19d5c4ebadbee0f73a9fcde36ab57d4d3f66ee1a81e1df2386ee1afbb965eadc1126013a7db21e7674222e7cbf5c2667b98e169fdc0e57720767fabd6c1b840

test:
  secret_key_base: 2cf9366a6121c0a35c000e775e167d23b08e4eb7a053b6132e8efc74dfcc3d1e9d6668293336b85227d3cd30c46dfa460f51e3e7710c9695680cfd5712b1bc86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
